Repository Molivair/outpaintings, pull requests merged in 2023-01, with the labels that each got.

#3 chore: update README.md file
  README.md
Labels: documentation

#15 chore: add LICENSE file
  LICENSE
  LICENSE_CC_BY_NC_4.0
Labels: enhancement

#16 feat: add collection.md file
  collection.md
  prompts.md
Labels: enhancement

#20 fix: rename LICENSE_CC_BY_NC_4.0 to LICENSE
  LICENSE
  README.md
Labels: bug

#23 feat: add ada123cd game changer gem
  gems/.gitkeep
  gems/ada123cd-game-changer.png
Labels: enhancement

#36 feat: add opensea's links into README.md file
  collection.md
Labels: enhancement

#38 bump: release version 1.0.0
  CHANGELOG.md
  VERSION
Labels: documentation
